# Generated by Django 6.0 on 2025-12-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_marca_producto_precio_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_costo',
        ),
    ]
