# Generated by Django 6.0 on 2025-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Compra'),
        ),
    ]
