# Generated by Django 6.0 on 2026-01-14 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0007_presupuesto_detallepresupuesto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APERTURA", "Apertura / Saldos Iniciales"),
                            ("NORMAL", "Movimiento Normal"),
                            ("REFUNDICION", "Refundición de Resultados"),
                            ("CIERRE", "Cierre Patrimonial"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("creado_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("PN", "Patrimonio Neto"),
                            ("INGRESO", "Ingreso (Resultado Positivo)"),
                            ("EGRESO", "Egreso (Resultado Negativo)"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemAsiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "haber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.asiento",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.cuenta",
                    ),
                ),
            ],
        ),
    ]
