# Generated by Django 6.0 on 2026-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_cajadiaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="monto_efectivo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_mercadopago",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_transferencia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="vuelto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
