# Generated by Django 6.0 on 2026-01-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0010_venta_monto_efectivo_venta_monto_mercadopago_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        max_length=150, verbose_name="Razón Social / Nombre"
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="CUIT/DNI"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "condicion_iva",
                    models.CharField(
                        choices=[
                            ("RI", "Responsable Inscripto"),
                            ("MONOTRIBUTO", "Monotributo"),
                            ("EXENTO", "Exento"),
                        ],
                        default="MONOTRIBUTO",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
    ]
