# Generated by Django 6.0 on 2026-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0012_compra_detallecompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="descuento_porcentaje",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="venta",
            name="descuento_global",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
