# Generated by Django 6.0 on 2026-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0013_detalleventa_descuento_porcentaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="descuento_global_porcentaje",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
