# Generated by Django 6.0 on 2026-01-17 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                ("modulo", models.CharField(max_length=50)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREATE", "Alta"),
                            ("UPDATE", "Modificación"),
                            ("DELETE", "Eliminación"),
                            ("LOGIN", "Inicio de Sesión"),
                            ("LOGOUT", "Cierre de Sesión"),
                            ("AJUSTE", "Ajuste Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(max_length=50)),
                ("estado_anterior", models.JSONField(blank=True, null=True)),
                ("estado_nuevo", models.JSONField(blank=True, null=True)),
                ("cambios", models.JSONField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="auditoria_e_content_4e349f_idx",
                    ),
                    models.Index(
                        fields=["usuario"], name="auditoria_e_usuario_feee63_idx"
                    ),
                    models.Index(
                        fields=["accion"], name="auditoria_e_accion_739d33_idx"
                    ),
                ],
            },
        ),
    ]
